{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulnrelay.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vulnrelay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vulnrelay.fullname" . }}
  labels:
    {{- include "vulnrelay.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vulnrelay.fullname" . }}
  labels:
    {{- include "vulnrelay.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vulnrelay.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vulnrelay.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}