apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnrelay.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vulnrelay.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: metrics
  selector:
    {{- include "vulnrelay.selectorLabels" . | nindent 4 }}